Mvc5Demo/Models/Author.cs
namespace Mvc5Demo.Models;

public class Author
{
    public Author(int id, string name, ERole role)
    {
        Id = id;
        Name = name;
        Role = role;
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public ERole Role { get; set; }
}

Mvc5Demo/Models/Book.cs
namespace Mvc5Demo.Models;

public class Book
{
    public Book(int id, string title, int authorId, List<int> subscriberListById)
    {
        Id = id;
        Title = title;
        AuthorId = authorId;
        SubscriberListById = subscriberListById;
    }

    public int Id { get; set; }
    public string Title { get; set; }
    public int AuthorId { get; set; }
    public List<int> SubscriberListById { get; set; }
}

Mvc5Demo/Models/Customer.cs
namespace Mvc5Demo.Models;

public class Customer
{
    public Customer(string customerUserName, string customerPassword, string customerFullName, string customerPhoneNumber, string customerEmail)
    {
        CustomerUserName = customerUserName;
        CustomerPassword = customerPassword;
        CustomerFullName = customerFullName;
        CustomerPhoneNumber = customerPhoneNumber;
        CustomerEmail = customerEmail;
    }
    public Customer()
    {

    }

    public Customer(int customerId, string customerUserName, string customerPassword, string customerFullName, string customerPhoneNumber, string customerEmail)
    {
        CustomerId = customerId;
        CustomerUserName = customerUserName;
        CustomerPassword = customerPassword;
        CustomerFullName = customerFullName;
        CustomerPhoneNumber = customerPhoneNumber;
        CustomerEmail = customerEmail;
    }

    public int CustomerId { get; set; }
    public string CustomerUserName { get; set; }
    public string CustomerPassword { get; set; }
    public string CustomerFullName { get; set; }
    public string CustomerPhoneNumber { get; set; }
    public string CustomerEmail { get; set; }
}

Mvc5Demo/Models/Enums/ERole.cs
namespace Mvc5Demo.Models.Enums;

public enum ERole
{
    admin = 0,
    user = 1
}

Mvc5Demo/Models/ErrorViewModel.cs
namespace Mvc5Demo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Mvc5Demo/Models/Temperature.cs
namespace Mvc5Demo.Models;

public class Temperature
{
    public static double CelciusToFahrenheit(double Tc)
    {
        double Tf;
        Tf = (Tc*9/5) + 32;
        return Tf;
    }
}

Mvc5Demo/Controllers/AuthorsController.cs
namespace Mvc5Demo.Controllers;

[ApiController]
[Route("api/[controller]")]
public class AuthorsController : Controller
{
    private readonly IAuthorService _authorService;
    public AuthorsController(IAuthorService authorService)
    {
        _authorService = authorService;
    }

    [HttpGet]
    public async Task<IActionResult> GetAllAuthors()
    {
        var authors = await _authorService.GetAllAuthors();

        return Ok(authors);
    }
}

Mvc5Demo/Controllers/BooksController.cs
namespace Mvc5Demo.Controllers;

[ApiController]
[Route("api/[controller]")]
public class BooksController : Controller
{
    private readonly IBookService _bookService;
    private readonly IAuthorService _authorService;
    public BooksController(IBookService bookService, IAuthorService authorService)
    {
        _bookService = bookService;
        _authorService = authorService;
    }

    [HttpGet("author")]
    public async Task<IActionResult> GetListBooks([FromQuery] int id)
    {
        var authorRole = _authorService.FindAuthorRoleById(id);
        if (authorRole.Result == ERole.admin)
        {
            var books = await _bookService.GetListBooks();
            return Ok(books);
        }
        else if (authorRole.Result == ERole.user)
        {
            var books = await _bookService.GetLimitedBooks(id);
            return Ok(books);
        }
        else return BadRequest();
    }

    [HttpGet]
    public async Task<IActionResult> GetAllBooks()
    {
        var books = await _bookService.GetListBooks();
        return Ok(books);
    }
}

Mvc5Demo/Controllers/HomeController.cs
namespace Mvc5Demo.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Temperature()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Mvc5Demo/Controllers/MockController.cs
namespace Mvc5Demo.Controllers;

[ApiController]
[Route("[controller]")]
public class MockController : Controller
{
    private readonly IMockService _mockService;
    public MockController(IMockService mockService)
    {
        _mockService = mockService;
    }

    [HttpGet]
    public IActionResult Mock()
    {
        return View();
    }

    [HttpGet("JsonData")]
    public async Task<IActionResult> HttpClientGetJsonObjects()
    {
        var objects = await _mockService.MockJsonData();
        return Ok(objects);
    }

    [HttpGet("SpecialBlog")]
    public async Task<IActionResult> SpecialBlog()
    {
        var str = await _mockService.SpecialBlog();
        return Ok(str);
    }

    [HttpGet("MockData")]
    public async Task<IActionResult> MockData()
    {
        var data = await _mockService.MockData();
        return Ok(data);
    }

    [HttpGet("ErrorCode")]
    public async Task<IActionResult> ErrorCode()
    {
        var errorCode = await _mockService.ErrorCode();
        return Ok(errorCode);
    }
    
    [HttpGet("Temperature/{tc}")]
    public IActionResult TemperatureConversion(double tc)
    {
        var tf = Temperature.CelciusToFahrenheit(tc);

        return Ok("Fahrenheit: " + tf.ToString());
    }
}

Mvc5Demo/Views/Home/HttpClientDemo.cshtml
@*@page "/demo"
@inject IHttpClientFactory _clientFactory

<h3>Mock Data</h3>
@code{
    protected override Task OnInitAsync(){
        var request = new HttpRequestMessage(HttpMethod.Get,
            "https://deliverywebapi.azurewebsites.net/api/customers");

        var client = _clientFactory.CreateClient
    }
}*@

Mvc5Demo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">ALL HAIL HYDRA</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mvc5Demo/Views/Mock/Mock.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">THIS IS THE MOCK WEB UI FOR MVC</h1>
    <p>Information about <a href="https://developers.google.com/blogger/docs/3.0/using">Google developer blogger</a>.</p>
    <p>Information about <a href="https://umbraco.com/blog/">Umbraco blogs</a>.</p>
    <p>Get method <a href="https://deliverywebapi.azurewebsites.net/api/orders?minimal=true">Mock Api</a>.</p>
</div>

Mvc5Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc5Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc5Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc5Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mock" asp-action="Mock">Mock Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mock" asp-action="MockData">Test IHttpClientFactory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mock" asp-action="SpecialBlog">Special Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mock" asp-action="ErrorCode">Error Code</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mock" asp-action="HttpClientGetJsonObjects">DEMO TEST 2 CÁI CLIENT</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mvc5Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>